title: Resident Evil Complete Lore
email: your-email@example.com
description: ""
author: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
